name = "evarena"
main = "dist/index.html"
site = { include = "dist" }

[build]
command = "npm run build"
cwd = "./"

[env.production]
name = "evarena-prod"
route = "https://evarena.io/*"
zone_id = ""

[env.staging]
name = "evarena-staging"
route = "https://staging.evarena.io/*"
zone_id = ""
